name: PR Workflow by ${{ github.actor }}

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  GITHUB_ACTIONS: true

jobs:
  github-task-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Show GITHUB_ACTIONS variable
        run: echo "GITHUB_ACTIONS=$GITHUB_ACTIONS"

      - name: Show branch and repository name
        run: echo "Branch: ${{ github.ref }} | Repository: ${{ github.repository }}"

      - name: Show event name
        run: echo "Event: ${{ github.event_name }}"
